name: timetable
description: Flutter package to create a Timetable Widget that display blocks of widgets inside a timetable.
version: 1.0.0
repository: https://github.com/Iconica-Development/timetable

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
