name: timetable_example
description: Timetable Widget

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_timetable_view:
    path: ../
  flutter_timetable_interface:
    path: ../../flutter_timetable_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
