name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
      - feature/*
      - bugfix/*
      - hotfix/*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper
            /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter format
        run: flutter format -o none --set-exit-if-changed .
      - name: Flutter analyze
        run: flutter analyze
